In [ ]:
# 67
#Preprocesar datasets para ML
#Modulo sklearn.preprocessing 
#Escalamiento: modifica la escala  un rango determinado, usualmente 0 y 1
# clase MinMaxScaler
# Estandarizacion: Transforma datos con distrubucion gaussiana y medias diferentes a med=0 y desv=1
#clase StandardScaler
#Normalizacion: Reescalar cada observacion a una longitud de 1 (norma o vector unitario)
# clase Normalizer
#Binarizacion: tranforma el tipo de dato a binario
#clase Binarizar
# Imputacion: Sustituir datos faltantes
# Centrado: Remover el valor medios de cada variable y escalarlo dividiendo las variables no contantes por su desviacion estandar


In [5]:
#Reescala de datos
# Biblioteca: Numpy, Pandas y scikit-learn(clase MinMaxScaler)
#Reescala entre 0 y 1
from pandas import read_csv
from numpy import  set_printoptions
from sklearn.preprocessing import MinMaxScaler
filename='diabetes.csv'
names=['preg', 'plas', 'pres', 'skin', 'test', 'mass','pedi', 'age','class']
dataframe=read_csv(filename, names=names)
array=dataframe.values
X=array[:,0:8]
y=array[:,8]
scaler=MinMaxScaler(feature_range=(0,1))
rescaledX=scaler.fit_transform(X)
set_printoptions(precision=3)
print(rescaledX[0:6,:])

[[0.353 0.744 0.59  0.354 0.    0.501 0.234 0.483]
 [0.059 0.427 0.541 0.293 0.    0.396 0.117 0.167]
 [0.471 0.92  0.525 0.    0.    0.347 0.254 0.183]
 [0.059 0.447 0.541 0.232 0.111 0.419 0.038 0.   ]
 [0.    0.688 0.328 0.354 0.199 0.642 0.944 0.2  ]
 [0.294 0.583 0.607 0.    0.    0.382 0.053 0.15 ]]


In [6]:
#Reescala de datos
# Biblioteca: Numpy, Pandas y scikit-learn(clase MinMaxScaler)
#Reescala entre 0 y 1
from pandas import read_csv
from numpy import  set_printoptions
from sklearn.preprocessing import MinMaxScaler
filename='iris_01.csv'
names=['sepal_length', 'selpal_width', 'petal_length', 'petal_width','class']
dataframe=read_csv(filename, names=names)
array=dataframe.values
X=array[:,0:4]
y=array[:,4]
scaler=MinMaxScaler(feature_range=(0,1))
rescaledX=scaler.fit_transform(X)
set_printoptions(precision=3)
print(rescaledX[0:6,:])

[[0.222 0.625 0.068 0.042]
 [0.167 0.417 0.068 0.042]
 [0.111 0.5   0.051 0.042]
 [0.083 0.458 0.085 0.042]
 [0.194 0.667 0.068 0.042]
 [0.306 0.792 0.119 0.125]]


In [9]:
# EStandarizacion de Datos
# Estandarizacion: Transforma datos con distrubucion gaussiana y medias diferentes a med=0 y desv=1
#clase StandardScaler
from pandas import read_csv
from numpy import  set_printoptions
from sklearn.preprocessing import StandardScaler
filename='diabetes.csv'
names=['preg', 'plas', 'pres', 'skin', 'test', 'mass','pedi', 'age','class']
dataframe=read_csv(filename, names=names)
array=dataframe.values
X=array[:,0:8]
y=array[:,8]
scaler=StandardScaler().fit(X)
rescaledX=scaler.fit_transform(X)
set_printoptions(precision=3)
print(rescaledX[0:5,:])

[[ 0.64   0.848  0.15   0.907 -0.693  0.204  0.468  1.426]
 [-0.845 -1.123 -0.161  0.531 -0.693 -0.684 -0.365 -0.191]
 [ 1.234  1.944 -0.264 -1.288 -0.693 -1.103  0.604 -0.106]
 [-0.845 -0.998 -0.161  0.155  0.123 -0.494 -0.921 -1.042]
 [-1.142  0.504 -1.505  0.907  0.766  1.41   5.485 -0.02 ]]


In [10]:
# EStandarizacion de Datos
# Estandarizacion: Transforma datos con distrubucion gaussiana y medias diferentes a med=0 y desv=1
#clase StandardScaler
from pandas import read_csv
from numpy import  set_printoptions
from sklearn.preprocessing import StandardScaler
filename='iris_01.csv'
names=['sepal_length', 'selpal_width', 'petal_length', 'petal_width','class']
dataframe=read_csv(filename, names=names)
array=dataframe.values
X=array[:,0:4]
y=array[:,4]
scaler=StandardScaler().fit(X)
rescaledX=scaler.fit_transform(X)
set_printoptions(precision=3)
print(rescaledX[0:6,:])


[[-0.901  1.019 -1.34  -1.315]
 [-1.143 -0.132 -1.34  -1.315]
 [-1.385  0.328 -1.397 -1.315]
 [-1.507  0.098 -1.283 -1.315]
 [-1.022  1.249 -1.34  -1.315]
 [-0.537  1.94  -1.17  -1.052]]


In [11]:
#Normalizar Datos
#Normalizacion: Reescalar cada observacion a una longitud de 1 (norma o vector unitario)
# clase Normalizer
from pandas import read_csv
from numpy import  set_printoptions
from sklearn.preprocessing import Normalizer
filename='diabetes.csv'
names=['preg', 'plas', 'pres', 'skin', 'test', 'mass','pedi', 'age','class']
dataframe=read_csv(filename, names=names)
array=dataframe.values
X=array[:,0:8]
y=array[:,8]
scaler=Normalizer().fit(X)
rescaledX=scaler.fit_transform(X)
set_printoptions(precision=3)
print(rescaledX[0:5,:])

[[0.034 0.828 0.403 0.196 0.    0.188 0.004 0.28 ]
 [0.008 0.716 0.556 0.244 0.    0.224 0.003 0.261]
 [0.04  0.924 0.323 0.    0.    0.118 0.003 0.162]
 [0.007 0.588 0.436 0.152 0.622 0.186 0.001 0.139]
 [0.    0.596 0.174 0.152 0.731 0.188 0.01  0.144]]


In [15]:
#Normalizar Datos
#Normalizacion: Reescalar cada observacion a una longitud de 1 (norma o vector unitario)
# clase Normalizer
from pandas import read_csv
from numpy import  set_printoptions
from sklearn.preprocessing import Normalizer
filename='iris_01.csv'
names=['sepal_length', 'selpal_width', 'petal_length', 'petal_width','class']
dataframe=read_csv(filename, names=names)
array=dataframe.values
X=array[:,0:4]
y=array[:,4]
scaler=Normalizer().fit(X)
rescaledX=scaler.fit_transform(X)
set_printoptions(precision=3)
print(rescaledX[0:5,:])


[[0.804 0.552 0.221 0.032]
 [0.828 0.507 0.237 0.034]
 [0.805 0.548 0.223 0.034]
 [0.8   0.539 0.261 0.035]
 [0.791 0.569 0.221 0.032]]


In [14]:
#Binarizacion de datos
#Binarizacion: tranforma el tipo de dato a binario
#clase Binarizar
from pandas import read_csv
from numpy import  set_printoptions
from sklearn.preprocessing import Binarizer
filename='diabetes.csv'
names=['preg', 'plas', 'pres', 'skin', 'test', 'mass','pedi', 'age','class']
dataframe=read_csv(filename, names=names)
array=dataframe.values
X=array[:,0:8]
y=array[:,8]
binarizer=Binarizer(threshold=0.0).fit(X)
binaryX=binarizer.transform(X)
set_printoptions(precision=3)
print(binaryX[0:5,:])

[[1. 1. 1. 1. 0. 1. 1. 1.]
 [1. 1. 1. 1. 0. 1. 1. 1.]
 [1. 1. 1. 0. 0. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 1. 1. 1. 1. 1. 1. 1.]]


In [16]:
#Binarizacion de datos
#Binarizacion: tranforma el tipo de dato a binario
#clase Binarizar
from pandas import read_csv
from numpy import  set_printoptions
from sklearn.preprocessing import Binarizer
filename='iris_01.csv'
names=['sepal_length', 'selpal_width', 'petal_length', 'petal_width','class']
dataframe=read_csv(filename, names=names)
array=dataframe.values
X=array[:,0:4]
y=array[:,4]
binarizer=Binarizer(threshold=0.0).fit(X)
binaryX=binarizer.transform(X)
set_printoptions(precision=3)
print(binaryX[0:6,:])

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
